---
title: "DiscriminantePCA"
author: "Engels Emiliano Miranda Palacios A01423398"
date: "2023-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(ggplot2)
library(MVN)
```

## Scores
```{r}
datos <- read.csv("datosConsolidados.csv")
head(datos)
```

```{r}
datos = datos[datos$zona!="GA",]
datos
```

```{r}
z_norm<-function(x){(x-mean(x))/sd(x)}
cols = c("TOUT", "RH", "SR", "NOPPM", "NO2PPM", "NOXPPM", "SO2PPM")
M1=as.data.frame(lapply(datos[c(cols)],z_norm)) # x es la base de datos
M1
```


```{r}
PCA = princomp(M1)
summary(PCA)
comp = PCA$scores[,1:3]
```
```{r}
comp = data.frame(comp) 
comp["zona"] = datos$zona
comp
```

```{r}
cols = c("TOUT", "RH", "SR", "NOPPM", "NO2PPM", "NOXPPM", "SO2PPM")
color = c(CA='blue', GA = 'green', SA = 'orange')
col.ind = color[comp$zona]
plot(datos[cols],pch=21,bg=col.ind, col='gray')
```


```{r}
# modelo LDA

lda.model = lda(zona~.,data = comp)

#output



lda.model
```

```{r}
predicted = predict(lda.model)

names(predicted)

head(predicted$class)
head(predicted$posterior)
head(predicted$x)
```



```{r}
ldahist(data=predicted$x[,1], g = comp$zona, type='both', main='Histograma de la función discriminante LD1')
```


```{r}
plot(LD2~LD1, data = predicted$x, pch =21, col='gray', bg = col.ind, main = 'Valores discriminantes en las observaciones')
```




```{r}

#Creamos un vector con el color corresponidente a cada observacion de acuerdo a la columna Species
col.ind2=color[predicted$class]

#Graficos de dispersion con el color de acuerdo al tipo de especie
plot(datos[cols], pch=21, bg=col.ind,col= "grey", main= "normal" )
plot(datos[cols], pch=21, bg=col.ind2,col= "grey", main="predicted")
```


```{r}
table(pred=predicted$class, true=comp$zona)
# porcentaje de observaciones clasificadas erróneamente
rate=1-mean(predicted$class==comp$zona)
cat("\n El porcentaje de observaciones clasificadas erróneamente es: ",rate,"%")
```


